from odoo import models, fields


class FirstEnergyForm(models.Model):
    _name = 'custom.first.energy.form'
    _description = 'First Energy Form'

    # Link to CRM
    lead_id = fields.Many2one('crm.lead', string='Lead')

    # Workflow
    stage = fields.Selection([
        ('1', 'Stage 1'),
        ('2', 'Stage 2'),
        ('3', 'Stage 3'),
        ('4', 'Stage 4'),
        ('5', 'Stage 5')
    ], string='Stage', required=True)
    internal_dnc_checked = fields.Date(string="Internal DNC Checked")
    existing_sale = fields.Char(string="Existing Sale with NMI & Phone Number")
    online_enquiry_form = fields.Char(string="Online Enquiry Form")
    vendor_id = fields.Char(string="Vendor ID")
    agent = fields.Char(string="Agent")
    channel_ref = fields.Char(string="Channel Reference")
    sale_ref = fields.Char(string="Sale Reference")
    lead_ref = fields.Char(string="Lead Ref (External)")  # renamed to avoid clash
    incentive = fields.Char(string="Incentive")
    sale_date = fields.Date(string="Date of Sale")
    campaign_ref = fields.Char(string="Campaign Reference")
    promo_code = fields.Char(string="Promo Code")
    current_elec_retailer = fields.Char(string="Current Electric Retailer")
    current_gas_retailer = fields.Char(string="Current Gas Retailer")
    multisite = fields.Boolean(string="Multisite")
    existing_customer = fields.Boolean(string="Existing Customer")
    customer_account_no = fields.Char(string="Customer Account Number")
    customer_type = fields.Selection([
        ('resident', 'Resident'),
        ('company', 'Company'),
    ], string='Customer Type', default="resident")
    account_name = fields.Char(string="Account Name")
    abn = fields.Char(string="ABN")
    acn = fields.Char(string="ACN")
    business_name = fields.Char(string="Business Name")
    trustee_name = fields.Char(string="Trustee Name")
    trading_name = fields.Char(string="Trading Name")
    position = fields.Char(string="Position")
    sale_type = fields.Selection([
        ('transfer', 'Transfer'),
        ('movein', 'Movein')
    ], string="Sale Type", default="transfer")
    title = fields.Char(string="Title")
    first_name = fields.Char(string="First Name")
    last_name = fields.Char(string="Last Name")
    phone_landline = fields.Char(string="Phone Landline")
    phone_mobile = fields.Char(string="Mobile Number")
    auth_date_of_birth = fields.Date(string="Authentication Date of Birth")
    auth_expiry = fields.Date(string="Authentication Expiry")
    auth_no = fields.Char(string="Authentication No")
    auth_type = fields.Char(string="Authentication Type")
    email = fields.Char(string="Email")
    life_support = fields.Boolean(string="Life Support", default=False)
    concessioner_number = fields.Char(string="Concessioner Number")
    concession_expiry = fields.Date(string="Concession Expiry Date")
    concession_flag = fields.Boolean(string="Concession Flag", default=False)
    concession_start_date = fields.Date(string="Concession Start Date")
    concession_type = fields.Char(string="Concession Type")
    conc_first_name = fields.Char(string="Concession First Name")
    conc_last_name = fields.Char(string="Concession Last Name")
    secondary_title = fields.Char(string="Secondary Title")
    sec_first_name = fields.Char(string="Secondary First Name")
    sec_last_name = fields.Char(string="Secondary Last Name")
    sec_auth_date_of_birth = fields.Date(string="Secondary Authentication DOB")
    sec_auth_no = fields.Char(string="Secondary Authentication No")
    sec_auth_type = fields.Char(string="Secondary Authentication Type")
    sec_auth_expiry = fields.Date(string="Secondary Authentication Expiry")
    sec_email = fields.Char(string="Secondary Email")
    sec_phone_home = fields.Char(string="Secondary Phone Home")
    sec_mobile_number = fields.Char(string="Secondary Mobile Number")
    site_apartment_no = fields.Char(string="Site Apartment Number")
    site_apartment_type = fields.Char(string="Site Apartment Type")
    site_building_name = fields.Char(string="Site Building Name")
    site_floor_no = fields.Char(string="Site Floor Number")
    site_floor_type = fields.Char(string="Site Floor Type")
    site_location_description = fields.Text(string="Site Location Description")
    site_lot_number = fields.Char(string="Site Lot Number")
    site_street_number = fields.Char(string="Site Street Number")
    site_street_name = fields.Char(string="Site Street Name")
    site_street_number_suffix = fields.Char(string="Site Street Number Suffix")
    site_street_type = fields.Char(string="Site Street Type")
    site_street_suffix = fields.Char(string="Site Street Suffix")
    site_suburb = fields.Char(string="Site Suburb")
    site_state = fields.Char(string="Site State")
    site_post_code = fields.Char(string="Site Post Code")
    gas_site_apartment_number = fields.Char(string="Gas Site Apartment Number")
    gas_site_apartment_type = fields.Char(string="Gas Site Apartment Type")
    gas_site_building_name = fields.Char(string="Gas Site Building Name")
    gas_site_floor_number = fields.Char(string="Gas Site Floor Number")
    gas_site_floor_type = fields.Char(string="Gas Site Floor Type")
    gas_site_location_description = fields.Char(string="Gas Site Location Description")
    gas_site_lot_number = fields.Char(string="Gas Site Lot Number")
    gas_site_street_name = fields.Char(string="Gas Site Street Name")
    gas_site_street_number = fields.Char(string="Gas Site Street Number")
    gas_site_street_number_suffix = fields.Char(string="Gas Site Street Number Suffix")  # typo fixed
    gas_site_street_type = fields.Char(string="Gas Site Street Type")
    gas_site_street_suffix = fields.Char("Gas Site Street Suffix")
    gas_site_suburb = fields.Char("Gas Site Suburb")
    gas_site_state = fields.Char("Gas Site State")
    gas_site_post_code = fields.Char("Gas Site Post Code")
    network_tariff_code = fields.Char("Network Tariff Code")
    nmi = fields.Char("NMI")
    mirn = fields.Char("MIRN")
    fuel = fields.Char("Fuel")
    feed_in = fields.Char("Feed In")
    annual_usage = fields.Float("Annual Usage")
    gas_annual_usage = fields.Float("Gas Annual Usage")
    product_code = fields.Char("Product Code")
    gas_product_code = fields.Char("Gas Product Code")
    offer_description = fields.Text("Offer Description")
    gas_offer_description = fields.Text("Gas Offer Description")
    green_percent = fields.Float("Green Percent")
    proposed_transfer_date = fields.Date("Proposed Transfer Date")
    gas_proposed_transfer_date = fields.Date("Gas Proposed Transfer Date")
    bill_cycle_code = fields.Char("Bill Cycle Code")
    gas_bill_cycle_code = fields.Char("Gas Bill Cycle Code")
    average_monthly_spend = fields.Float("Average Monthly Spend")
    is_owner = fields.Boolean("Is Owner")
    has_accepted_marketing = fields.Boolean("Has Accepted Marketing")
    email_account_notice = fields.Boolean("Email Account Notice")
    email_invoice = fields.Boolean("Email Invoice")
    billing_email = fields.Char("Billing Email")
    postal_building_name = fields.Char("Postal Building Name")
    postal_apartment_number = fields.Char("Postal Apartment Number")
    postal_apartment_type = fields.Char("Postal Apartment Type")
    postal_floor_number = fields.Char("Postal Floor Number")
    postal_floor_type = fields.Char("Postal Floor Type")
    postal_lot_no = fields.Char("Postal Lot No")
    postal_street_number = fields.Char("Postal Street Number")
    postal_street_number_suffix = fields.Char("Postal Street Number Suffix")
    postal_street_name = fields.Char("Postal Street Name")
    postal_street_type = fields.Char("Postal Street Type")
    postal_street_suffix = fields.Char("Postal Street Suffix")
    postal_suburb = fields.Char("Postal Suburb")
    postal_post_code = fields.Char("Postal Post Code")
    postal_state = fields.Char("Postal State")
    comments = fields.Text("Comments")
    transfer_special_instructions = fields.Text("Transfer Special Instructions")
    medical_cooling = fields.Boolean("Medical Cooling")
    medical_cooling_energy_rebate = fields.Boolean("Medical Cooling Energy Rebate")
    benefit_end_date = fields.Date("Benefit End Date")
    sales_class = fields.Char("Sales Class")
    bill_group_code = fields.Char("Bill Group Code")
    gas_meter_number = fields.Char("Gas Meter Number")
    centre_name = fields.Char("Centre Name")
    qc_name = fields.Char("QC Name")
    verifiers_name = fields.Char("Verifier’s Name")
    tl_name = fields.Char("TL Name")
    dnc_ref_no = fields.Char("DNC Ref No")
    audit_2 = fields.Char("Audit-2")
    welcome_call = fields.Boolean("Welcome Call")
